#version: '3.8'
services:
  smart-room-allocation:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Database Configuration (Supabase)
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      # Email Configuration
      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST}
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:-true}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:-true}

#      #HIKARI CONFIGURATION
#      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 2
#      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 30000
#      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: 600000
#      SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: 300000
#      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: 0
#      SPRING_DATASOURCE_HIKARI_CONNECTION_TEST_QUERY: SELECT 1
#      SPRING_DATASOURCE_HIKARI_LEAK_DETECTION_THRESHOLD: 2000
      # JWT Configuration
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    networks:
      - app-network
networks:
  app-network:
    driver: bridge